#!/bin/bash
# bkup_proj
#
# 
# SYNOPSIS:
#
#     ./bkup_proj [ t [ d ] ]
# 
# 
# DESCRIPTION:
#
#     Copies the iOS project to a backup directory corresponding to 
#     the current timestamp & optionally creates a tarball of it.
#     [ g ]   Ignore git files.
#     [ t ]   Generate a tarball of the backup.
#     [ d ]   Remove the copied contents after archival.

#
# 
# EXAMPLE:
# 
#     Backs up the contents, then tarballs it.
#     bkup_proj -t
# 

# [=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=]
# [=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=]

# -[ usage error ]-
usage_msg=`echo "USAGE:"; echo "bkup_proj [ g ] [ t [ d ] ]"; echo "bkup_proj -td"`
# [=-=-=-=-=-=-=-=-=-=-=-=-=-=-=]



# -[ project attribs ]-
proj_name="GUTZ"
proj_root="`dirname $0`/../.."
ignore_path="02_DEV/bash/.ignore.bkup"
bkup_path="04_BACKUP"
# [=-=-=-=-=-=-=-=-=-=-=-=-=-=-=]


#-- printf "proj_name:[%s]\n" $proj_name
#-- printf "proj_root:[%s]\n" $proj_root
#-- printf "ignore_path:[%s]\n" $ignore_path
#-- printf "bkup_path:[%s]\n" $bkup_path

# -[ option flags ]-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-\_
g_flag=false #-- git
t_flag=false #-- tarball
d_flag=false #-- delete
# -=-=-=-=-=-=-=-=-=-=-=-=-/⁻


# \\ [ option parser ]\_
# \\~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~\_
while getopts 'gtd' OPTION; do #-//> there's a '-t'
	case $OPTION in #-/> set flag based on char
		
		g) # )-/> passed in '-g'
			g_flag=true
			;;
		
		
		t) # )-/> passed in '-t'
			t_flag=true
			;;
			
		
		d) # )-/> passed in '-d'
			d_flag=true
			;;
		
		?) # )-/> passed in all others '-?'
			echo $usage_msg
			exit 1
			;;
	esac
done
# //~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~/⁻



# -[ timestamping ]-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-\_
date_dir=`date +%Y%m%d` #-- YYYYMMDD
time_dir=`date +%H%M%S` #-- HHMMSS
ts=$(echo "${date_dir}_${time_dir}")
# -=-=-=-=-=-=-=-=-=-=-=-=-/⁻


# -[ script setup ]-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-\_
echo $'\ec' #-- clear stdout

# current dir not script's, change over
if [ `pwd` != `dirname $0` ]; then
	cd `dirname $0`; fi

#-- printf "Moving into project sources... [%s/]\n" "${proj_src}"
#-- cd "${proj_src}" #-- change to the proj's top-lvl

printf "Moving into project root... [%s/]\n" "${proj_root}"
cd "${proj_root}"

if [ ! -d $bkup_path ]; then #))-\> create top-lvl backup dir
	printf "Creating top-lvl backup dir... [%s/]\n" $bkup_path
	mkdir "${bkup_path}"; fi

if [ ! -d $bkup_path/$date_dir ]; then #))-\> create the date dir if needed
	printf "Creating date dir... [%s/]\n" $date_dir
	mkdir "${bkup_path}/${date_dir}"; fi
# -=-=-=-=-=-=-=-=-=-=-=-=-/⁻

# -[ backup init ]-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-\_
printf "Creating time dir... [%s/]\n" $time_dir
mkdir "${bkup_path}/${date_dir}/${time_dir}" #-- create the time dir


if $g_flag ; then
	ignore_path="02_DEV/bash/.ignore_git.bkup"; fi
	


printf "Copying project contents... "
rsync -h -v -r --exclude-from "${ignore_path}" . "${bkup_path}/${date_dir}/${time_dir}" #-- use rsync to copy, preserving ts / recurse & exclude any svn meta data w/ verbose
# -=-=-=-=-=-=-=-=-=-=-=-=-/⁻


# \\ [ archive creation ]\_
# \\~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~\_
if $t_flag ; then #))-\> create tarball
	
	tar_name="${proj_name}_[${date_dir}-${time_dir}].tar" #-- archive name
	printf "\nCreating tarball from contents...\n"
	tar -cf "${bkup_path}/${date_dir}/${tar_name}" "${bkup_path}/${date_dir}/${time_dir}" #-- create tarball w/ contents
	
	printf "\nAdding write permission on tarball for group & other users...\n"
	chmod 766 "${bkup_path}/${date_dir}/${tar_name}"
	
	if $d_flag ; then #))-\> remove backup contents
		printf "Removing time dir w/ contents...\n"
		rm -Rf "${bkup_path}/${date_dir}/${time_dir}"; fi
fi
# //~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~/⁻



# -[ script termination ]-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-\_
printf "Completed backup, now terminating...\n"
exit 0; #-- complete w/o error
# -=-=-=-=-=-=-=-=-=-=-=-=-/⁻



#rsync -h -v -r --exclude="- .svn*" --exclude="- .DS_Store" . "${bkup_path}/${date_dir}/${time_dir}" #-- use rsync to copy, preserving ts / recurse & exclude any svn meta data w/ verbose
#rsync -h -v -r --exclude="- .svn*" --exclude="- .DS_Store" "../PARTS" "${bkup_path}/${date_dir}/${time_dir}" #-- use rsync to copy, preserving ts / recurse & exclude any svn meta data w/ verbose